# Generated by Django 4.1.3 on 2022-11-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('mouvement', models.CharField(choices=[('1', 'Entree'), ('2', 'Sortie')], max_length=20)),
            ],
        ),
    ]
