# Generated by Django 4.1.3 on 2022-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_reportmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='Description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
