# Generated by Django 4.1.3 on 2022-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_reportmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='Description',
            field=models.TextField(max_length=200),
        ),
    ]
